language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: kmeZa3gRcsdlvNAyPIZFTMpjC8U/TKuf8DimTxsryjmwsByrc3Z56FDVZloIw/g4nhpC8WAEjKmp0qaolqI08GHu/aQbL22RGPguNg907P4gHTCNdfOpb5MI4lsxT9gjkdqBlYeRcG7zqXs4sRX7xi9DZd29O4qXHD3pUF5BJo/3ndSvrjSzqYmhtZsrKTP5VVd2lck6TIaURLZ/i4BqvzvrRQCQjxrmEpTkt8SEc5Kg+CP9zzjI1FD+vdBZ26W5ki1dfVZaxtfwbhNGB9DZjzxkX5W3qCAHmUqUpNxWvkUhVpHpFbif8Iv6A9nfrtBfOFyKFCwHJgmnZ4xSwtB8P7zC2UqpK8QKA22BwDmIA+DS+YhkK5G4/r6wG7Y+vZmdiaGRYUEAxRhkgMXVD4M0OTRYDLEV79J2LKUWzf6kShzMsiQqNqUPbbrdi02Z/RfNTz7C6T7HoBnd635OCu82p9gRpN9JWzTTdj5DlYKRz7yAEFJ7Qa18G3FSdWt+ETrwrIhjR/rwbh6udOdne25tCstgxE1Li8kU96FE5IIlLFDF6hhVSKee1oRqO3/aPbb3B9lYvwTUgTU5JygfQbXbOXWG3NZKrpSwKBYdQ/FnrlKpla7j8AbuGOpf8SgVPaRoxlcrialB64LNUk8fXoom8WnV1vOgnjoFssvzHeguUTQ=
  project: mining-889ab
  skip_cleanup: true
env:
  global:
    secure: KfghvyZBRrJdOmhpMMH9WQBthAs+fj1FXuJ/670Y2rnqddKwlWEWrqnzXrmySar4UXmut6pchGytewhQhHG1WmXVLxbRY/k3e1vOVXMeNzjSPyLOIF32QYpdHSgOoPVhrhp09tp9Tt41Dhcll0vULS0z3sxyZY03sKV21OXT9eX5mzUPPCGm8TWci7ZpxlcraFJfRoOWmWiJxpWGbDgKu3rK4ZfWNGaQ0ZJK5vdS+ZsondmOtEfTtcDKzYIDZhNfk1cqLLLnBXTf43d0Ad5hlF8Xn116NPZhhrbLoUDIw1W80DEnpFPqnbze89D6ykK1gwgisyMlqJjYmcR+/yd3RPrgl4hQBOS7mD/fHZrT/6sOCdo1OT1iPlxuDz1Ydc6mQHyra7HgbhuQPJrtMvIPMIiJK1o1oc7L98l906qCVRkYecHNVdtqdwm5FPqZ+Tq2NCBUD0u0x6t0auiATX9uOj3eHkt/P+x7V9HmvxPZDThn1zeAF8EAIW0gkQoYEnH/E/5jTBxlj3maAPHn9OnQ5oY0yR1w17m+K8iOAcFx2MVplwUQfceArA7QAkfzrobRgl/5jeG2Gm/r9n8cxqCp7yTodi/sbdbXx1T9viO9zbISc+q+z0XsSKtGDP0NhSCypxMNCL87fXZKD0DRQczx0ld9erhIwVxm2y8alVk6mlE=
before_install:
  - sudo apt-get update
recipients:
      - midan888@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
